# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: PSpeters.Pastebird
PackageVersion: 1.4.0
MinimumOSVersion: 10.0.22000.0
InstallerType: inno
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- DisplayName: Pastebird
  Publisher: Pastebird
  ProductCode: '{23DB349F-5518-4A51-BF10-39BBB4178412}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/pspeters/pastebird/releases/download/v1.4.0/PastebirdSetup-1.4.0.exe
  InstallerSha256: B56E255B858D439A08EA7959A12F80A941727CA1C41D4501064FD52F560309FC
  ProductCode: '{23DB349F-5518-4A51-BF10-39BBB4178412}_is1'
ManifestType: installer
ManifestVersion: 1.10.0
